---
- name: Setup Httpd And Open Firewalld Port
  hosts: all
  become: true
  tasks:
    - name: Update apt cache only (Ubuntu only)
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600  # Avoids frequent updates if cache is fresh
      when: ansible_distribution == "Ubuntu"

    - name: Install Apache Package (Ubuntu only)
      ansible.builtin.apt:
        name: apache2
        state: present
      when: ansible_distribution == "Ubuntu"

    - name: Start Apache Service
      ansible.builtin.service:
        name: apache2
        state: started
      when: ansible_distribution == "Ubuntu"

    - name: Open Port 80 For Http Access
      ansible.posix.firewalld:
        service: http
        permanent: true
        state: enabled
      when: ansible_facts['os_family'] == "RedHat"

    - name: Restart Firewalld Service To Apply Changes
      ansible.builtin.service:
        name: firewalld
        state: reloaded
      when: ansible_facts['os_family'] == "RedHat"
