---
- name: Install Apache on all hosts
  hosts: all
  become: true
  tasks:

    - name: Install Apache2 Package (Ubuntu)
      ansible.builtin.package:
        name:
          - "{{ apache_package }}"
          - "{{ php_package }}"
        state: present
        update_cache: true
