---
- name: Install Updates For Ubuntu
  hosts: web_servers
  become: true
  tasks:
    - name: Install Updates For Ubuntu
      tags: always
      ansible.builtin.apt:
        upgrade: dist
        update_cache: true
      when: ansible_distribution == "Ubuntu"

- name: Install Apache on Web Servers
  hosts: web_servers
  become: true
  tasks:
    - name: Install Apache On Web Servers (Ubuntu)
      tags: apache,ubuntu
      ansible.builtin.apt:
        name:
          - apache2
          - libapache2-mod-php
        state: present
      when: ansible_distribution == "Ubuntu"

    - name: Install Apache On Web Servers (AlmaLinux)
      tags: apache,almalinux
      ansible.builtin.dnf:
        name: httpd
        state: present
      when: ansible_distribution == "AlmaLinux"

    - name: Ensure Apache Is Running (Ubuntu)
      tags: apache,ubuntu
      ansible.builtin.service:
        name: apache2
        state: started
      when: ansible_distribution == "Ubuntu"

    - name: Ensure Apache  Is Running (AlmaLinux)
      tags: apache, AlmaLinux
      ansible.builtin.service:
        name: httpd
        state: started
      when: ansible_distribution == "AlmaLinux"

    - name: Copy HTML File For Site
      tags: apache,ubuntu
      ansible.builtin.copy:
        src: default_site.html
        dest: /var/www/html/index.html
        owner: molapo
        group: molapo
        mode: '0644'

- name: Install MariaDB on DB Servers
  hosts: db_servers
  become: true
  tasks:
    - name: Install MariaDB Package On Db Servers
      tags: DB
      ansible.builtin.dnf:
        name: mariadb
        state: present
      when: ansible_distribution == "AlmaLinux"
